# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'joshfalgout/fargate'

steps:
- task: CmdLine@2
  displayName: skip ssl
  inputs:
    script: 'echo insecure >> $HOME/.curlrc'

- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: ./Dockerfile


- task: prisma-cloud-compute-scan@2
  inputs:
    scanType: 'images'
    twistlockService: 'compute-console-connection'
    artifact: $(imageName):$(Build.BuildId)
